# Generated by Django 5.1.4 on 2024-12-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0002_remove_user_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tc',
            field=models.BooleanField(default=True),
        ),
    ]
